### PR TITLE
created div on index for messages and built function that will show m…

### PR DESCRIPTION
**Pull request by wppattonjr**
…esages on the dom

### CODE REVIEW

**Review by wmmcinturff — APPROVED** [review]
Everything looks good. I approve.

**Comment by drteresavasquez** [comment]
What issue ticket is this attached to?

**Comment by wppattonjr** [comment]
This is a function that when called will print elements to the DOM.

## Description


## Related Issue
#28 #18 

## Motivation and Context
Various elements will need to be printed to the DOM so that the user can interact with the application.

## How Can This Be Tested?
This will be able to be tested once there is data present to be printed to the DOM.

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

**Review by liz-barnes — APPROVED** [review]
👍

**Pull request merged**
